# Generated by Django 2.0.5 on 2018-05-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=11, null=True)),
                ('destination', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(null=True)),
                ('record_type', models.SmallIntegerField(choices=[(1, 'start'), (2, 'end')])),
                ('timestamp', models.DateTimeField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Call')),
            ],
        ),
    ]
